stages:
  - name: generate
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
         theta: {stages: init, output: theta, unwrap: true}
         phi: {stages: init, output: phi, unwrap: true}
         n_samples: {stages: init, output: n_samples, unwrap: true}
         outfile: '{workdir}/out.np'
      step: {$ref: 'steps.yml#/weinberg'}